(()=>{'use strict';const passwordLength=8;const message=(form,text,error=false)=>{let box=form.querySelector('.form-message');box.textContent=text;box.classList.toggle('error',error)};const setBusy=(button,on,label)=>{button.disabled=on;if(on){button.dataset.label=button.textContent;button.textContent=label}else button.textContent=button.dataset.label};const emailOK=value=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);const logError=(context,error)=>console.error(context,{code:error?.code||error?.error_code,status:error?.status,message:error?.message,details:error?.details,hint:error?.hint,error});const registrationMessage=error=>{let code=error?.code||error?.error_code,text=String(error?.message||'').toLowerCase();if(code==='over_email_send_rate_limit'||text.includes('email rate limit'))return 'Too many verification emails have been requested. Please wait and try again later.';if(code==='email_exists'||text.includes('already registered'))return 'An account already exists for this email. Please sign in or reset your password.';if(text.includes('redirect'))return 'Registration confirmation is not configured for this site address. Please contact the administrator.';if(text.includes('database error saving new user'))return 'Your account could not be created because profile setup was rejected. Please contact the administrator.';return 'We could not create your account right now. Please try again later.'};

async function loadBlocks(){const select=document.querySelector('#block');if(!select)return;try{const {data,error}=await db.from('hostel_blocks').select('id,name').order('name');if(error)throw error;select.innerHTML='<option value="">Select your hostel block</option>'+(data||[]).map(block=>`<option value="${block.id}">${String(block.name).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}</option>`).join('');if(!data?.length){select.innerHTML='<option value="">No hostel blocks are available</option>';select.disabled=true}}catch(error){logError('Unable to load hostel blocks',error);select.innerHTML='<option value="">Unable to load hostel blocks</option>';select.disabled=true;message(document.querySelector('#register-form'),'Hostel blocks could not be loaded. Please try again later.',true)}}

async function completeStudentProfile(user,fields){const {data:existing,error:lookupError}=await db.from('profiles').select('id').eq('id',user.id).maybeSingle();if(lookupError)throw lookupError;const profile={role:'student',full_name:fields.fullName,roll_number:fields.rollNumber,block_id:fields.blockId,room_number:fields.roomNumber};const result=existing?await db.from('profiles').update(profile).eq('id',user.id):await db.from('profiles').insert({id:user.id,...profile});if(result.error)throw result.error}

function setupRegistration(){const form=document.querySelector('#register-form');if(!form)return;loadBlocks();form.addEventListener('submit',async event=>{event.preventDefault();const fullName=form.querySelector('#full-name').value.trim(),rollNumber=form.querySelector('#roll-number').value.trim(),email=form.querySelector('#email').value.trim(),password=form.querySelector('#password').value,confirmation=form.querySelector('#confirm-password').value,blockId=form.querySelector('#block').value,roomNumber=form.querySelector('#room-number').value.trim(),button=form.querySelector('button');if(!fullName||!rollNumber||!email||!password||!confirmation||!blockId||!roomNumber)return message(form,'Please complete every required field.',true);if(!emailOK(email))return message(form,'Enter a valid student email address.',true);if(password.length<passwordLength)return message(form,'Password must be at least 8 characters long.',true);if(password!==confirmation)return message(form,'Passwords do not match.',true);message(form,'');try{setBusy(button,true,'Creating account…');const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:`${window.location.origin}/student-login.html`,data:{role:'student',full_name:fullName,roll_number:rollNumber,block_id:blockId,room_number:roomNumber,registration_source:'student-registration'}}});if(error)throw error;if(data.session){await completeStudentProfile(data.user,{fullName,rollNumber,blockId,roomNumber});window.location.replace('student-dashboard.html');return}message(form,'Account created. Please check your email and verify your account before signing in.')}catch(error){logError('Student registration failed',error);message(form,registrationMessage(error),true)}finally{setBusy(button,false)}})}

function setupForgotPassword(){const form=document.querySelector('#forgot-password-form');if(!form)return;form.addEventListener('submit',async event=>{event.preventDefault();const email=form.querySelector('#email').value.trim(),button=form.querySelector('button');if(!emailOK(email))return message(form,'Enter a valid student email address.',true);try{setBusy(button,true,'Sending link…');const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password.html`});if(error)throw error;message(form,'If an account exists for this email, a password reset link has been sent.')}catch(error){message(form,'We could not send a reset link right now. Please try again later.',true)}finally{setBusy(button,false)}})}

function setupPasswordReset(){const form=document.querySelector('#reset-password-form');if(!form)return;let recoveryReady=false;const markRecovery=session=>{recoveryReady=Boolean(session)};db.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY')markRecovery(session)});db.auth.getSession().then(({data:{session}})=>{if(session)markRecovery(session);else message(form,'This password reset link is missing, invalid, or has expired.',true)}).catch(()=>message(form,'This password reset link is invalid or has expired.',true));form.addEventListener('submit',async event=>{event.preventDefault();const password=form.querySelector('#password').value,confirmation=form.querySelector('#confirm-password').value,button=form.querySelector('button');if(!recoveryReady)return message(form,'This password reset link is missing, invalid, or has expired.',true);if(password.length<passwordLength)return message(form,'Password must be at least 8 characters long.',true);if(password!==confirmation)return message(form,'Passwords do not match.',true);try{setBusy(button,true,'Updating password…');const {error}=await db.auth.updateUser({password});if(error)throw error;message(form,'Your password has been updated. You can now sign in.');button.hidden=true}catch(error){message(form,'We could not update your password. Request a new reset link and try again.',true)}finally{if(!button.hidden)setBusy(button,false)}})}

document.addEventListener('DOMContentLoaded',()=>{setupRegistration();setupForgotPassword();setupPasswordReset()})})();
